server.port=8080

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:database-archery}:${POSTGRES_PORT:5432}/${POSTGRES_DB:archeryDb}
spring.datasource.username=${POSTGRES_USER:archeryUser}
spring.datasource.password=${POSTGRES_PASSWORD:12345}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.enabled=false
spring.sql.init.mode=never

# MongoDB
spring.mongodb.uri=mongodb://mongo-archery:27017,mongo-archery-secondary:27017/archerydb?replicaSet=rs0
spring.mongodb.database=archerydb
spring.data.mongodb.auto-index-creation=true